### ISSUE TITLE
Milestone: Version 1.0.0

### ISSUE THREAD

**Issue by iduuck** [iDuuck/sketchjs#1]
Some improvements need to be done in favour of our first stable version launch _(List will be extended over time)_.
#### Enhancements
- [ ] More default options (?)
- [ ] More methods (JSON export, etc.)
- [x] Remove `sketchtool` and create `install.sh`
#### Bugs
- [x] Make tests stable

**Comment by cognitom** [comment]
Hi @iDuuck, how about #3?
Even if you're the author of `sketchtools`, it feels something unfair.

**Comment by iduuck** [comment]
Yeah, I am working on this, when I have time :)

**Comment by cognitom** [comment]
Thanks for your feedback :-)

I used this strategy in another product, Just FYI:

``` json
{
  "scripts": {
    "postinstall": "curl -L https://cognitom.github.io/tokoro/dist/data-v02.zip > data.zip; unzip -oq data.zip -d data; rm data.zip"
  }
}
```

https://github.com/cognitom/tokoro/blob/master/package.json#L12

If you like it, I can send PR.

**Comment by iduuck** [comment]
@cognitom **Any** PR is appreciated :)
